name: pycigar

dependencies:
    - python==3.6.8
    - scipy==1.1.0
    - lxml==4.2.4
    - six==1.11.0
    - path.py
    - python-dateutil==2.7.3
    - cloudpickle==1.2.1
    - setuptools==41.0.0
    - pip:
        - ray==0.8.2
        - tensorflow==2.0.0
        - gym==0.14.0
        - pyprind==2.11.2
        - nose2==0.8.0
        - cached_property
        - joblib==0.14.0
        - matplotlib==3.0.0
        - tabulate
        - dill
        - lz4
        - setproctitle
        - psutil
        - opencv-python
        - boto3==1.4.8
        - redis~=3.3.2
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - opendssdirect.py==0.3.7
        - tqdm
